# Generated by Django 3.2.4 on 2021-06-28 12:47

import cms.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=8, null=True)),
                ('mobile_no', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('sender_name', models.CharField(max_length=200, null=True)),
                ('sender_contact_no', models.CharField(max_length=200, null=True)),
                ('sender_email', models.CharField(max_length=200, null=True)),
                ('sender_address', models.CharField(max_length=200, null=True)),
                ('receiver_name', models.CharField(max_length=200, null=True)),
                ('receiver_contact_no', models.CharField(max_length=200, null=True)),
                ('receiver_email', models.CharField(max_length=200, null=True)),
                ('receiver_address', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('id', models.CharField(default=cms.models.create_id, editable=False, max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_fn', models.CharField(max_length=200, null=True)),
                ('bill_sn', models.CharField(max_length=200, null=True)),
                ('bill_email', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField()),
                ('pay_method', models.CharField(choices=[('COD', 'COD'), ('Credit Card', 'Credit Card'), ('Paypal', 'Paypal')], max_length=200, null=True)),
                ('pay_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], max_length=200, null=True)),
                ('shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.delivery')),
            ],
        ),
    ]
