# Generated by Django 3.2.4 on 2021-06-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_payment_pay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Credit Card', 'Credit Card'), ('Paypal', 'Paypal')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=11),
        ),
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.FloatField(default=500),
        ),
    ]
