# Generated by Django 3.2.4 on 2021-06-30 14:29

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_payment_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default=cms.models.create_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
